# Julia for Travis: http://docs.travis-ci.com/user/languages/julia/

language: julia
julia:
  - 1.0
  - 1.1
  - 1.2

jobs:
  include:
    - stage: Documentation
      julia: 1.2
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate()'
        - julia --project=docs --color=yes docs/make.jl
