name = "AlgebraicNets"
uuid = "d77033f9-55b8-43bc-9cdc-5e0578f628dc"
authors = ["Evan Patterson <evan@epatters.org>"]
version = "0.1.0"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
