name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.0', '1.3', '1.4']
        os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      # XXX: Julia 1.0 does not use the Project.toml in `tests` directory.
      #- name: "Run tests"
      #  uses: julia-actions/julia-runtest@master
      - name: "Run tests"
        run: |
          julia -e 'using Pkg; Pkg.activate("test"); Pkg.develop(PackageSpec(path="."))'
          julia --color=yes --check-bounds=yes --project=test test/runtests.jl
